from __future__ import annotations

from pathlib import Path

from openstyle.models import DesignTokens


def write_readme_en(
    target_dir: Path,
    *,
    bundle_folder_name: str,
    bundle_title_zh: str,
    bundle_title_en: str,
    bundle_slug: str,
    template_variant: str,
    source_template_dir: Path,
    tokens: DesignTokens,
) -> None:
    """Write an English README next to DESIGN.md and preview files."""
    title = bundle_title_en.replace("-", " ").title() if bundle_title_en else bundle_slug.replace("-", " ").title()
    lines = [
        f"# {title}",
        "",
        "This folder was generated by **OpenStyle** from an HTML website template. It contains a summarized design-system document and static preview pages derived from the template’s HTML/CSS.",
        "",
        "## Source",
        "",
        f"- **Bundle directory:** `{bundle_folder_name}`",
        f"- **Bundle title (cleaned):** {bundle_title_zh}",
        f"- **English slug:** `{bundle_slug}`",
        f"- **Template variant / subfolder:** `{template_variant}`",
        f"- **Resolved path:** `{source_template_dir}`",
        "",
        "## Generated files",
        "",
        "| File | Description |",
        "|------|-------------|",
        "| `DESIGN.md` | Nine-part design spec (colors, typography, layout, etc.) inferred from CSS. |",
        "| `preview.html` | Light-themed token showcase page. |",
        "| `preview-dark.html` | Dark-themed variant with remapped surface/shadow tokens. |",
        "",
        "## How to view",
        "",
        "Open `preview.html` or `preview-dark.html` in a browser (double-click or serve locally). Relative asset links from the original template are not embedded here—this is a **design snapshot**, not a full site copy.",
        "",
        "## Extracted summary",
        "",
        f"- **Token name in DESIGN.md:** {tokens.template_name}",
        f"- **Color groups:** {', '.join(sorted(tokens.colors.keys())) or '—'}",
        f"- **Detected components:** {', '.join(c.name for c in tokens.components) or '—'}",
        "",
    ]
    (target_dir / "README.md").write_text("\n".join(lines), encoding="utf-8")
